spring.application.name=employee-data-service
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_data_service
spring.datasource.username=employee_data_service
spring.datasource.password=localdev
spring.jpa.hibernate.ddl-auto=update
app.encryption.key=${SSN_ENCRYPTION_KEY}
